<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Image\5050.png" />
    <None Remove="Assets\Image\5050used.png" />
    <None Remove="Assets\Image\ALTP_LOGO.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_1.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_10.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_11.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_12.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_2.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_3.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_4.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_5.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_6.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_7.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_8.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_9.png" />
    <None Remove="Assets\Image\Calling.png" />
    <None Remove="Assets\Image\Callingused.png" />
    <None Remove="Assets\Image\KhanGia.png" />
    <None Remove="Assets\Image\KhanGiaused.png" />
    <None Remove="Assets\Image\Lai_Van_Sam.png" />
    <None Remove="Assets\Image\Nguoi_choi.png" />
    <None Remove="Assets\Image\ToTuVan.png" />
    <None Remove="Assets\Image\ToTuVanused.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Image\5050.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\5050used.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_LOGO.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_11.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_12.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\Calling.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\KhanGia.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\KhanGiaused.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\Lai_Van_Sam.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\Nguoi_choi.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Image\Callingused.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ToTuVan.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ToTuVanused.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Verify.CommunityToolkit.Mvvm" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Config\" />
    <Folder Include="Assets\Saves\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Data\questions_11_15.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Data\questions_1_5.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Data\questions_6_10.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
