<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Audio\BGM\Q1_Q5.mp3" />
    <None Remove="Assets\Audio\BGM\Q6_Q15.mp3" />
    <None Remove="Assets\Audio\SFX\Answer\Tra_Loi_Dung_1_den_4.mp3" />
    <None Remove="Assets\Audio\SFX\Answer\Tra_Loi_Dung_Cau_15.mp3" />
    <None Remove="Assets\Audio\SFX\Answer\Tra_Loi_Dung_Cau_5_Va_10.mp3" />
    <None Remove="Assets\Audio\SFX\Answer\Tra_Loi_Dung_Cau_6_Den_14.mp3" />
    <None Remove="Assets\Audio\SFX\Answer\Tra_Loi_Sai_1_5.mp3" />
    <None Remove="Assets\Audio\SFX\Answer\Tra_Loi_Sai_Cau_15.mp3" />
    <None Remove="Assets\Audio\SFX\Answer\Tra_Loi_Sai_Cau_6_Den_14.mp3" />
    <None Remove="Assets\Audio\SFX\Bat_Dau_Game.mp3" />
    <None Remove="Assets\Audio\SFX\Help\hoiykienkhangiatrongtruongquay.mp3" />
    <None Remove="Assets\Audio\SFX\Help\loaibo2phuongansai.mp3" />
    <None Remove="Assets\Audio\VA\Answer\dapana.mp3" />
    <None Remove="Assets\Audio\VA\Answer\dapanb.mp3" />
    <None Remove="Assets\Audio\VA\Answer\dapanc.mp3" />
    <None Remove="Assets\Audio\VA\Answer\dapand.mp3" />
    <None Remove="Assets\Audio\VA\Answer\dolacautraloidung.mp3" />
    <None Remove="Assets\Audio\VA\bandavuotqua5cauhoidautiencuachuongtrinh.mp3" />
    <None Remove="Assets\Audio\VA\chaomungdenvoichuongtrinhailatrieuphu.mp3" />
    <None Remove="Assets\Audio\VA\chaomungquividenvoichuongtrinhailatrieuphu.mp3" />
    <None Remove="Assets\Audio\VA\Help\dung5050.mp3" />
    <None Remove="Assets\Audio\VA\Help\dunggoidienthoaichonguoithan.mp3" />
    <None Remove="Assets\Audio\VA\Help\dunghoiykienkhangiatrongtruongquay.mp3" />
    <None Remove="Assets\Audio\VA\Help\dungtotuvantaicho.mp3" />
    <None Remove="Assets\Audio\VA\phobienluatchoi.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoidautien.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso10.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso11.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso12.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso13.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso14.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso15.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso2.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso3.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso4.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso5.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso6.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso7.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso8.mp3" />
    <None Remove="Assets\Audio\VA\Question\cauhoiso9.mp3" />
    <None Remove="Assets\Audio\VA\vabatdautucauso6dolatotuvantaicho.mp3" />
    <None Remove="Assets\Image\5050.png" />
    <None Remove="Assets\Image\5050used.png" />
    <None Remove="Assets\Image\ALTP_LOGO.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_1.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_10.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_11.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_12.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_2.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_3.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_4.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_5.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_6.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_7.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_8.png" />
    <None Remove="Assets\Image\ALTP_Nostalgia_9.png" />
    <None Remove="Assets\Image\Calling.png" />
    <None Remove="Assets\Image\Callingused.png" />
    <None Remove="Assets\Image\KhanGia.png" />
    <None Remove="Assets\Image\KhanGiaused.png" />
    <None Remove="Assets\Image\Lai_Van_Sam.png" />
    <None Remove="Assets\Image\Nguoi_choi.png" />
    <None Remove="Assets\Image\ToTuVan.png" />
    <None Remove="Assets\Image\ToTuVanused.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Audio\BGM\Q1_Q5.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\BGM\Q6_Q15.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Answer\Tra_Loi_Cau_6_Den_15.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Answer\Tra_Loi_Dung_1_den_4.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Answer\Tra_Loi_Dung_Cau_15.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Answer\Tra_Loi_Dung_Cau_5_Va_10.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Answer\Tra_Loi_Dung_Cau_6_Den_14.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Answer\Tra_Loi_Sai_1_5.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Answer\Tra_Loi_Sai_Cau_15.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Answer\Tra_Loi_Sai_Cau_6_Den_14.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Bat_Dau_Game.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Help\hoiykienkhangiatrongtruongquay.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Help\loaibo2phuongansai.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SFX\Question\Bat_dau_cau_hoi.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Answer\dapana.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Answer\dapanb.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Answer\dapanc.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Answer\dapand.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Answer\dolacautraloidung.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\bandavuotqua5cauhoidautiencuachuongtrinh.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\chaomungquividenvoichuongtrinhailatrieuphu.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Help\dung5050.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Help\dunggoidienthoaichonguoithan.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Help\dunghoiykienkhangiatrongtruongquay.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Help\dungtotuvantaicho.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\phobienluatchoi.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoidautien.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso10.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso11.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso12.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso13.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso14.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso15.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso2.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso3.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso4.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso5.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso6.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso7.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso8.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\Question\cauhoiso9.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\VA\vabatdautucauso6dolatotuvantaicho.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\5050.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\5050used.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_LOGO.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_11.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_12.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ALTP_Nostalgia_9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\Calling.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\KhanGia.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\KhanGiaused.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\Lai_Van_Sam.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\Nguoi_choi.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Image\Callingused.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ToTuVan.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Image\ToTuVanused.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Verify.CommunityToolkit.Mvvm" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Config\" />
    <Folder Include="Assets\Saves\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Data\questions_11_15.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Data\questions_1_5.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Data\questions_6_10.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
